# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirEducationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=100)),
                ('college_start_date', models.DateField()),
                ('major', models.CharField(max_length=45)),
                ('college_end_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dir_education_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirEmploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100)),
                ('employment_start_date', models.DateTimeField()),
                ('job_title', models.CharField(max_length=80)),
                ('employment_end_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dir_employment_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirPersonnel',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45, unique=True)),
                ('openid', models.CharField(blank=True, db_column='openID', max_length=45, null=True, unique=True)),
                ('header_url', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('middle_name', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=45)),
                ('province_state', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('occupation', models.CharField(max_length=45)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('self_introduction', models.CharField(blank=True, max_length=1000, null=True)),
                ('executive_team_member', models.CharField(blank=True, max_length=10, null=True)),
                ('creation_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dir_personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=80)),
                ('task_description', models.CharField(max_length=250)),
                ('signup_due_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dir_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirTaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dir_task_assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirTeam',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=80)),
                ('team_description', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dir_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_status', models.CharField(choices=[('Accept', 'Accepted'), ('Reject', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=45)),
                ('contact_information', models.CharField(blank=True, max_length=80, null=True)),
                ('self_introduction', models.CharField(blank=True, max_length=1000, null=True)),
                ('creation_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'dir_team_member',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
